# specify which database and adapter to use for which environment

development:
  adapter: sqlite3
  database: db/gsd-development

test:
  adapter: sqlite3
  database: db/gsd-test

production:
  adapter: sqlite3
  database: db/gsd-production
